version: "3.8"

services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=app_db
    depends_on:
      - db
    networks:
      - internals

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: app_db
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internals

  frontend-secure:
    build:
      context: ./frontend-secure
      dockerfile: Dockerfile
    ports:
      - "8443:443"
    networks:
      - internals

volumes:
  db-data: 

networks:
  internals:
